### ISSUE TITLE
Best genome lost

### ISSUE THREAD

**Issue by zammbi** [wagenaartje/neataptic#28] opened 2017-06-14 11:08 UTC
I'm training by NEAT and I've seen that the best genome disappears. The same data is being used and I have 10% of the population as elitism. 

For example my console logging shows: 
> Generation: 3 - average score: -966.382
> Fittest score: -955.400, Best genome, nodes length: 6, nodes connections: 5
> Generation: 4 - average score: -954.417
> Fittest score: -213.391, Best genome, nodes length: 6, nodes connections: 5
> Generation: 5 - average score: -978.215
> Fittest score: -955.400, Best genome, nodes length: 6, nodes connections: 5
> Generation: 6 - average score: -965.121
> Fittest score: -955.400, Best genome, nodes length: 6, nodes connections: 5
>

I'm not sure if that is a bug or a feature. If this is a bug, I'll try to get more info if needed.

**Comment by wagenaartje** [comment] 2017-06-14 11:12
Hmm. This seems weird. The only thing I could think of is that genomes that have been selected by elitism _still_ undergo mutation with the probability of `mutationRate`. However, a score going from -213.391 to -955.400 is quite a big difference - but still, it could just be the mutation. How big is your population?

**Comment by zammbi** [comment] 2017-06-14 11:35
I've noticed this many times (it not a new bug but I think it has gotten worse), it just does randomly from what I can see. I do think it will be affecting how quickly it learns. Since the fittest was stuck at '-955.400' for some time.

This is my current setup. 
```
    neat = new Neat(5, 1, null, {
        mutation: Methods.Mutation.ALL,
        mutationRate: 0.5,
        popsize: 100,
        elitism: 10,
        selection: Methods.Selection.FITNESS_PROPORTIONATE,
    });
```

**Comment by zammbi** [comment] 2017-06-14 11:42
"However, a score going from -213.391 to -955.400 is quite a big difference"
usually, it is a small difference.

**Comment by wagenaartje** [comment] 2017-06-14 12:24
"Usually, it is a small difference."
Hmm, if that's the case - it might just be the mutation as I thought. Having a `mutationRate` of 0.5 gives a 50% chance of the fittest genome mutating.

On the other hand, I did some more research on elitism:

> Elitism only means that the most fit handful of individuals are guaranteed a place in the next generation - generally without undergoing mutation.  [source](https://stackoverflow.com/questions/14622342/elitism-in-ga-should-i-let-the-elites-be-selected-as-parents)

So I am in two minds if elitist genomes should still have a chance to be mutated.

**Comment by zammbi** [comment] 2017-06-14 12:33
Another example.

```
Generation: 296 - average score: -1098.957
Fittest score: -622.668, Best genome, nodes length: 10, nodes connections: 12

Generation: 297 - average score: -1061.358
Fittest score: -526.846, Best genome, nodes length: 10, nodes connections: 12

Generation: 298 - average score: -1038.978
Fittest score: -461.586, Best genome, nodes length: 10, nodes connections: 12

Generation: 299 - average score: -1001.351
Fittest score: -526.846, Best genome, nodes length: 11, nodes connections: 13

Generation: 300 - average score: -1017.179
Fittest score: -571.829, Best genome, nodes length: 9, nodes connections: 14

Generation: 301 - average score: -1062.201
Fittest score: -561.589, Best genome, nodes length: 9, nodes connections: 14

Generation: 302 - average score: -1066.946
Fittest score: -586.862, Best genome, nodes length: 8, nodes connections: 9

Generation: 303 - average score: -1008.721
Fittest score: -537.630, Best genome, nodes length: 8, nodes connections: 9

Generation: 304 - average score: -951.780
Fittest score: -547.714, Best genome, nodes length: 8, nodes connections: 11

Generation: 305 - average score: -940.166
Fittest score: -431.774, Best genome, nodes length: 11, nodes connections: 14

Generation: 306 - average score: -970.663
Fittest score: -445.763, Best genome, nodes length: 10, nodes connections: 12

Generation: 307 - average score: -948.772
Fittest score: -550.718, Best genome, nodes length: 8, nodes connections: 9
```

**Comment by wagenaartje** [comment] 2017-06-14 12:43
You have made me make up my mind: i'll make sure that in the NEAT and network.evolve() code, elitist genomes won't be mutated - and I hope that will fix it. I'll update it somewhere today.

Keep in mind that you are using a custom set up NEAT algorithm: you have to make this change yourself.

**Comment by zammbi** [comment] 2017-06-14 12:48
"Keep in mind that you are using a custom set up NEAT algorithm: you have to make this change yourself."
How would I do this?

**Comment by wagenaartje** [comment] 2017-06-14 13:39
Can you show me your main 'loop' code, which should look something like this:

```javascript
function endEvaluation(){
  console.log('Generation:', neat.generation, '- average score:', neat.getAverage());

  neat.sort();
  var newPopulation = [];

  // Elitism
  for(var i = 0; i < neat.elitism; i++){
    newPopulation.push(neat.population[i]);
  }

  // Breed the next individuals
  for(var i = 0; i < neat.popsize - neat.elitism; i++){
    newPopulation.push(neat.getOffspring());
  }

  // Replace the old population with the new population
  neat.population = newPopulation;
  neat.mutate();

  neat.generation++;
  startEvaluation();
```

**Comment by wagenaartje** [comment] 2017-06-14 18:22
Should be fixed as of https://github.com/wagenaartje/neataptic/commit/9ec007bbbfb923a48200affc0fd5f8891920d0d6

Notice that `mutate()` won't mutate the first N (N = elitism) individuals in the population now:

```javascript
    // Elitist genomes should not be included
    for(var i = this.elitism; i < this.popsize; i++){
      if(Math.random() <= this.mutationRate){
        for(var j = 0; j < this.mutationAmount; j++){
          var mutationMethod = this.mutation[Math.floor(Math.random() * this.mutation.length)];
          this.population[i].mutate(mutationMethod);
        }
      }
    }
```

**Comment by zammbi** [comment] 2017-06-15 08:36
@wagenaartje 
This is what I have:

```
    // Init new pop
    var newPopulation = [];

    // Elitism
    var i = 0;
    for (; i < neat.elitism; i++) {
        newPopulation.push(neat.population[i]);
    }

    // Breed the next individuals
    for (i = 0; i < neat.popsize - neat.elitism; i++) {
        newPopulation.push(neat.getOffspring());
    }

    // Replace the old population with the new population
    neat.population = newPopulation;
    neat.mutate();

    neat.generation++;
    startEvaluation();
```

**Comment by wagenaartje** [comment] 2017-06-15 08:39
That's similar to the built-in loop, so no changes required. If all is good, the best genomes should say unaffected.

**Comment by zammbi** [comment] 2017-06-15 08:39
Nice work. I'll give it a try now.

**Comment by zammbi** [comment] 2017-06-15 08:41
@wagenaartje 
Error:
"node_modules\neataptic\src\neat.js:161
if(this.population[tthis.popsize-1].score == null){
ReferenceError: tthis is not defined"

**Comment by wagenaartje** [comment] 2017-06-15 08:42
Wow, a shame that travis didn't check that. I'm on it.

**Comment by wagenaartje** [comment] 2017-06-15 08:47
I just comitted https://github.com/wagenaartje/neataptic/commit/48a49e195deec26926a441dc04d98be4047508d5. Could you check if everything works?

**Comment by zammbi** [comment] 2017-06-15 08:59
Seems to be working :)

**Comment by zammbi** [comment] 2017-06-16 11:13
I still think something is not quite right. 

> Fittest score: -716.259, Best genome, nodes length: 23, nodes connections: 36
> Generation: 694 - average score: -876.612
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 35
> Generation: 695 - average score: -879.428
> Fittest score: -716.259, Best genome, nodes length: 26, nodes connections: 36
> Generation: 696 - average score: -887.854  
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 32
> Generation: 697 - average score: -870.628
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 35
> Generation: 698 - average score: -871.888
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 36
> Generation: 699 - average score: -853.060
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 36
> Generation: 700 - average score: -870.250
> Fittest score: -716.259, Best genome, nodes length: 25, nodes connections: 38
> Generation: 701 - average score: -884.768
> Fittest score: -715.229, Best genome, nodes length: 27, nodes connections: 39
> Generation: 702 - average score: -879.905
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 33
> Generation: 703 - average score: -878.601
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 34
> Generation: 704 - average score: -852.953
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 35
> Generation: 705 - average score: -842.614
> Fittest score: -679.346, Best genome, nodes length: 22, nodes connections: 37
> Generation: 706 - average score: -850.836
> Fittest score: -673.020, Best genome, nodes length: 22, nodes connections: 37
> Generation: 707 - average score: -843.712
> Fittest score: -666.997, Best genome, nodes length: 22, nodes connections: 38
> Generation: 708 - average score: -845.792
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 34
> Generation: 709 - average score: -856.573
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 34
> Generation: 710 - average score: -852.143
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 34
> Generation: 711 - average score: -858.579
> Fittest score: -607.927, Best genome, nodes length: 23, nodes connections: 36
> Generation: 712 - average score: -849.435
> Fittest score: -716.259, Best genome, nodes length: 20, nodes connections: 33
> Generation: 713 - average score: -842.547
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 33
> Generation: 714 - average score: -848.277
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 38
> Generation: 715 - average score: -832.674
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 38
> Generation: 716 - average score: -848.143
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 33
> Generation: 717 - average score: -853.477
> Fittest score: -716.259, Best genome, nodes length: 22, nodes connections: 38
> Generation: 718 - average score: -895.138
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 30
> Generation: 719 - average score: -869.210
> Fittest score: -716.259, Best genome, nodes length: 21, nodes connections: 30

**Comment by wagenaartje** [comment] 2017-06-16 11:44
Does your scoring function take account of the size of the genome?

**Comment by wagenaartje** [comment] 2017-06-16 15:20
Oke this is definitely a bug and I'm looking in to it.

**But**, keep in mind that recurrent genomes might change their activations between different generations and thus have a different activation - unless you have `clear` enabled.

**Comment by D-Nice** [comment] 2017-06-16 18:25
I have noticed the same issue as the OP. I've even tried a workaround of saving the fittest in a temporary variable, and re-inserting it into the population post mutation. It has generally helped immensely in keeping the best genome around and not mutating it, however, there still are rare instances, after hundreds of generations, where the best genome seems to be discarded/replaced by one with a much lower score :S.

Currently running 1.2.6, I will try the latest version, which seems to nullify mutations in the elites, if I understood the latest commits correctly.

**Comment by D-Nice** [comment] 2017-06-16 18:36
> You have made me make up my mind: i'll make sure that in the NEAT and network.evolve() code, elitist genomes won't be mutated - and I hope that will fix it. I'll update it somewhere today.

> Keep in mind that you are using a custom set up NEAT algorithm: you have to make this change yourself.

Could you elaborate more on this, so with this change, are you making it so that elite genomes don't partake in the mutation and propagation process? The way I've implemented it within the part that handles evolution is that all genomes randomly mutate/propagate as is expected (according to the set rates), and then thereafter, I re-insert the fittest into the population, which I think is better than excluding them from mutation or propagation, as it will adversely affect evolution if the most fittest are not part of it!

**Comment by wagenaartje** [comment] 2017-06-17 07:05
D-nice that sounds like a better solution. Right now, I insert the fittest genomes in the next population, but they still undergo crossover. But the ways are quite similar. I will change this as I created a few other bugs in one of the last updates, I will try to make a commit before tomorrow night (not at home right now).

**Comment by zammbi** [comment] 2017-06-17 10:36
"Could you set clear: true and see if it still happens."
Clear not in the documentation. But I gave it a try and nope.
https://wagenaartje.github.io/neataptic/docs/neat/

Using the latest version.
> Generation: 12694 - average score: -901.943
> Fittest score: -697.955, Best genome, nodes length: 34, nodes connections: 100
> 
> Generation: 12695 - average score: -891.019
> Fittest score: -693.584, Best genome, nodes length: 34, nodes connections: 101
> 
> Generation: 12696 - average score: -903.802
> Fittest score: -675.709, Best genome, nodes length: 34, nodes connections: 97
> 
> Generation: 12697 - average score: -900.065
> Fittest score: -696.573, Best genome, nodes length: 33, nodes connections: 100
> 
> Generation: 12698 - average score: -894.290
> Fittest score: -693.584, Best genome, nodes length: 33, nodes connections: 100
> 
> Generation: 12699 - average score: -902.105
> Fittest score: -692.985, Best genome, nodes length: 31, nodes connections: 93
> 
> Generation: 12700 - average score: -915.792
> Fittest score: -679.910, Best genome, nodes length: 32, nodes connections: 90
> 
> Generation: 12701 - average score: -918.570
> Fittest score: -694.015, Best genome, nodes length: 32, nodes connections: 98
> 
> Generation: 12702 - average score: -890.203
> Fittest score: -694.175, Best genome, nodes length: 31, nodes connections: 94
> 
> Generation: 12703 - average score: -901.126
> Fittest score: -693.145, Best genome, nodes length: 35, nodes connections: 103
> 
> Generation: 12704 - average score: -884.385
> Fittest score: -694.015, Best genome, nodes length: 32, nodes connections: 96

**Comment by wagenaartje** [comment] 2017-06-18 18:37
@zammbi. What is happening for you is _definitely_ recurrent networks having a different output. Previously, when elitist genomes were saved, their contextual memory was never cleared; they still remembered what they had outputted during the previous fitness function test.

However, I have added the `clear` option. When you set `clear: true` - it should work.

@D-Nice. Hmmm. This seems to be a different bug than zammbi's one, as for you it actually resets the best genome. Are you sure it isn't related to your side of the code?

**Comment by D-Nice** [comment] 2017-06-18 21:02
@wagenaartje Yes, after some additional tinkering, it seems there were some asynchronicity issues within my code, as I was constantly feeding updated data, and at times, it seems the data would come in, and be updated, midway through a population running its fitness function, and the data it relies on being changed.

**Comment by zammbi** [comment] 2017-06-19 09:03
"However, I have added the clear option. When you set clear: true - it should work."
It's learning so much better now.
But I'm still losing my best genome.

> Generation: 468 - average score: -184.447
> Fittest score: 34.116, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 469 - average score: -244.150
> Fittest score: 233.787, Best genome, nodes length: 6, nodes connections: 7
> 
> Generation: 470 - average score: -230.072
> Fittest score: 158.527, Best genome, nodes length: 6, nodes connections: 7
> 
> Generation: 471 - average score: -250.179
> Fittest score: 60.971, Best genome, nodes length: 6, nodes connections: 6
> 
> Generation: 472 - average score: -224.122
> Fittest score: 51.189, Best genome, nodes length: 6, nodes connections: 8
> 
> Generation: 473 - average score: -161.612
> Fittest score: 60.971, Best genome, nodes length: 6, nodes connections: 6
> 
> Generation: 474 - average score: -171.808
> Fittest score: 51.056, Best genome, nodes length: 6, nodes connections: 6
> 
> Generation: 475 - average score: -192.516
> Fittest score: 15.405, Best genome, nodes length: 6, nodes connections: 6
> 
> Generation: 476 - average score: -110.423
> Fittest score: 58.045, Best genome, nodes length: 6, nodes connections: 7
> 
> Generation: 477 - average score: -147.055
> Fittest score: 27.011, Best genome, nodes length: 6, nodes connections: 7
>

**Comment by wagenaartje** [comment] 2017-06-19 09:17
@zammbi oke, I think if your change your `endEvaluation` code it should work. Right now your code must be something like this:

```javascript
/** End the evaluation of the current generation */
function endEvaluation(){
  console.log('Generation:', neat.generation, '- average score:', Math.round(neat.getAverage()));
  console.log('Fittest score:', Math.round(neat.getFittest().score));

  // Sort the population by score
  neat.sort();

  // Draw the best genome
  drawGraph(neat.population[0].graph($('.best').width()/2, $('.best').height()/2), '.best');

  // Init new pop
  var newPopulation = [];

  // Elitism
  for(var i = 0; i < neat.elitism; i++){
    newPopulation.push(neat.population[i]);
  }

  // Breed the next individuals
  for(var i = 0; i < neat.popsize - neat.elitism; i++){
    newPopulation.push(neat.getOffspring());
  }

  // Replace the old population with the new population
  neat.population = newPopulation;
  neat.mutate();

  neat.generation++;
  startEvaluation();
}
```

Change it to this:

```javascript
/** End the evaluation of the current generation */
function endEvaluation(){
    console.log('Generation:', neat.generation, '- average score:', Math.round(neat.getAverage()));
    console.log('Fittest score:', Math.round(neat.getFittest().score));
    this.sort();

    var newPopulation = [];

    // Elitism
    var elitists = [];
    for(var i = 0; i < this.elitism; i++){
      elitists.push(this.population[i]);
    }

    // Breed the next individuals
    for(var i = 0; i < this.popsize - this.elitism; i++){
      newPopulation.push(this.getOffspring());
    }

    // Replace the old population with the new population
    this.population = newPopulation;
    this.mutate();

    for(var i = 0; i < elitists.length; i++){
      this.population.push(elitists[i]);
    }

    // Reset the scores
    for(var i = 0; i < this.population.length; i++){
      this.population[i].score = null;
    }

    this.generation++;
```
Notice how the elitist genomes are added _after_ mutation. This is what happens in the built-in `evolve()` function of NEAT as well.

**Comment by zammbi** [comment] 2017-06-19 09:24
I get this crash:
```
node_modules\neataptic\src\neat.js:139
      var score = this.fitness(genome);
                       ^

TypeError: this.fitness is not a function
    at Neat.evaluate (node_modules\neataptic\src\neat.js:139:24)
    at Neat.getFittest (node_modules\neataptic\src\neat.js:159:12)
    at learnDatra (app.js:273:30)
    at Parser.fs.createReadStream.pipe.on.on (app.js:229:13)
```

**Comment by wagenaartje** [comment] 2017-06-19 09:27
It seems like you are calling `getFittest()` without actually having assigned scores to the population. The code above works for me (i'm working on a new small project).

**Comment by zammbi** [comment] 2017-06-19 09:49
Silly me, I left out the call to `startEvaluation`.

**Comment by zammbi** [comment] 2017-06-19 10:02
I was just about to reply and say this problem was fixed. But then this happened...

> Generation: 2550 - average score: 7450.372
> Fittest score: 10271.717, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 2551 - average score: 8054.885
> Fittest score: 10271.717, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 2552 - average score: -249.543
> Fittest score: 354.313, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 2553 - average score: -269.568
> Fittest score: 340.177, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 2554 - average score: -256.487
> Fittest score: 312.722, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 2555 - average score: -218.833
> Fittest score: 304.344, Best genome, nodes length: 7, nodes connections: 8
> 
> Generation: 2556 - average score: -265.201
> Fittest score: 391.577, Best genome, nodes length: 7, nodes connections: 8
> 
> Generation: 2557 - average score: -245.418
> Fittest score: 356.824, Best genome, nodes length: 7, nodes connections: 7
> 
> Generation: 2558 - average score: -143.153
> Fittest score: 349.160, Best genome, nodes length: 7, nodes connections: 7

**Comment by wagenaartje** [comment] 2017-06-19 10:27
Hmmm. That seems extremely weird. It even seems like the population got reset or something. Are you testing neural networks againts a dynamic task (or a static one)?

**Comment by zammbi** [comment] 2017-06-19 10:39
It's a large static csv I've loaded in memory. I'm making it learn 1000 rows at a time. Only move to the next batch of rows if the score is positive.

**Comment by zammbi** [comment] 2017-06-19 10:50
What I could do, is get a small repeatable case for you to try.

**Comment by wagenaartje** [comment] 2017-06-19 11:02
That would be great. I can't seem to reproduce it on simple dataset. 

> Only move to the next batch of rows if the score is positive (after X cycles).

You're sure the problem isn't related to this?

**Comment by zammbi** [comment] 2017-06-19 11:05
"You're sure the problem isn't related to this?"
Fairly sure. But doesn't mean there isn't a hidden bug :)

**Comment by wagenaartje** [comment] 2017-06-20 09:11
Welp, the same just happened to me for the first time. Suddenly all genomes started behaving the same as they did in generation 1. I have no clue what is causing this, and i'm trying to figure it out.

**Comment by zammbi** [comment] 2017-06-20 10:37
Oh good that you saw the issue too. It seems to happen after some time. For my dataset, it seems to always do it.

**Comment by zammbi** [comment] 2017-06-21 11:51
Trying to debug this is tricky but looks like I had a small win. The bug doesn't happen for 
`mutation: Methods.Mutation.FFW` but it does for `mutation: Methods.Mutation.ALL`.

**Comment by zammbi** [comment] 2017-06-21 12:25
I was able to easily repeat the issue when I simplified it to: 
```
        mutation: [
            Methods.Mutation.ADD_SELF_CONN,
            Methods.Mutation.SUB_SELF_CONN,
        ],
```

**Comment by wagenaartje** [comment] 2017-06-21 19:26
I should definitely add `Methods.Mutation.SWAP_NODES` to `Methods.Mutation.ALL`, I can't remember why I didn't add it.

So once you crossed out `Methods.Mutation.ADD_SELF_CONN` the fitness never decreased? I'll try and see if the same happens for me.

**Comment by zammbi** [comment] 2017-06-21 21:03
"So once you crossed out Methods.Mutation.ADD_SELF_CONN the fitness never decreased? I'll try and see if the same happens for me."

It didn't when I used:
```
    Methods.Mutation.MOD_ACTIVATION.allowed = [        
        Methods.Activation.SELU,
        Methods.Activation.RELU,
    ]
```
But when I used all the activations then it happened again 👎

**Comment by zammbi** [comment] 2017-06-23 07:51
Would it help if I sent my project to you?

**Comment by wagenaartje** [comment] 2017-06-23 12:05
That would help a lot, because I can't reproduce it on a 'fixed' problem, only on a dynamic one (genome vs genome). It may help me detect a pattern in the problem.

**Comment by wagenaartje** [comment] 2017-08-05 15:47
Closing as not reproducable for now. Re-open when issue re-appears.

**Closed** 2017-08-05 15:47 UTC
