### ISSUE TITLE
Network.fromJSON sending a null Node

### ISSUE THREAD

**Issue by tbarross** [wagenaartje/neataptic#5] opened 2017-04-18 12:46 UTC
managed to capture this issue when running my Neat with all the mutations

![capture](https://cloud.githubusercontent.com/assets/11909606/25131226/db9568aa-243c-11e7-8c55-273ace1d2c7d.JPG)
![capture2](https://cloud.githubusercontent.com/assets/11909606/25131228/db983c38-243c-11e7-8279-a4ea3b81cd97.JPG)

on the second image one of the arrays has an index of -1 which causes it to send a null node and then not being able to Gate it on the first image.

is this the issue with the crossover that makes networks "infertile"? if so how could you provide an example on your wiki how to use the new functionality with the LSTM. really eager to try and use the LSTM

**Comment by wagenaartje** [comment] 2017-04-18 18:40
This is definetely not infertility. I thought I had fixed this problem during the development process, but I guess not. I know it is caused by the combination of `Methods.Mutation.ADD_GATE` and `Methods.Mutation.ADD_SELF_CONN`. I will try to reproduce the error.

**Comment by wagenaartje** [comment] 2017-04-19 09:41
I seem to have found the problem. I was splicing elements from an array without loop backwards. The proces towards fixing this bug might have also fixed some others though 👍 

Update coming soon!

**Comment by wagenaartje** [comment] 2017-04-19 09:55
Should be fixed with this commit (https://github.com/wagenaartje/neataptic/commit/2128981b19bc771ffcb9e2e9fa0188f287315b86)!

**Closed by wagenaartje** 2017-04-19 09:55 UTC
Labels: bug
