### ISSUE TITLE
Crash "Cannot read property 'connect' of undefined" 

### ISSUE THREAD

**Issue by zammbi** [wagenaartje/neataptic#26] opened 2017-06-11 06:32 UTC
On the latest version (1.2.21) I got a crash. This was in the console: 

```
New generation.
Generation: 3560 - average score: -725.144
Fittest score: -258.686, Best genome, nodes length: 8, nodes connections: 13
\node_modules\neataptic\src\network.js:107
    var connections = from.connect(to, weight);
                          ^
TypeError: Cannot read property 'connect' of undefined
    at Network.connect (\node_modules\neataptic\src\network.js:107:27)
    at Function.Network.crossOver (\node_modules\neataptic\src\network.js:1059:29)
    at Neat.getOffspring (\node_modules\neataptic\src\neat.js:107:21)
    at endEvaluation (\app.js:121:33)
    at learnDatra (\app.js:243:9)
    at Parser.fs.createReadStream.pipe.on.on (\app.js:186:13)
    at emitNone (events.js:110:20)
    at Parser.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
Waiting for the debugger to disconnect...
```

**Comment by wagenaartje** [comment] 2017-06-11 10:14
In the last version I changed the Network.crossOver, so the problem is in that function for sure. I'll be doing some debuggin today to see what the cause of the problem is. Are you having this error consistently?

**Comment by zammbi** [comment] 2017-06-11 10:45
"Are you having this error consistently?"
I got it twice and so I've stopped running my code currently.

"And which mutation methods do you allow"
These ones:
```
        Methods.Activation.LOGISTIC,
        Methods.Activation.STEP,
        Methods.Activation.GAUSSIAN,
        Methods.Activation.BIPOLAR,
        Methods.Activation.TANH,
        Methods.Activation.SOFTSIGN,
        Methods.Activation.SINUSOID,
        Methods.Activation.BIPOLAR_SIGMOID,
        Methods.Activation.HARD_TANH,
```

**Comment by wagenaartje** [comment] 2017-06-11 10:46
Oke. But those are activation methods, which mutation methods are you using?

**Comment by clive-g-brown** [comment] 2017-06-11 10:48
there a whizzy new activation just published, SELU. Looks interesting.

**Comment by zammbi** [comment] 2017-06-11 10:49
"But those are activation methods"
Whoops:
`Methods.Mutation.ALL`

**Comment by wagenaartje** [comment] 2017-06-11 10:57
@zammbi 

I'm on to it, I just managed to reproduce the error! It only occurs for me when two fitnesses are the same. So debugging now!

@clive-g-brown 
Seems interesting! I might implement it, after I read through the paper. https://www.reddit.com/r/MachineLearning/comments/6g5tg1/r_selfnormalizing_neural_networks_improved_elu/dio0qac/

**Comment by wagenaartje** [comment] 2017-06-11 12:31
Should be fixed as of https://github.com/wagenaartje/neataptic/commit/05bd932ae9991649cd51cdd74b48d6aa6ddda9fe

**Closed** 2017-06-11 12:30 UTC
Labels: bug

**Comment by zammbi** [comment] 2017-06-11 13:18
Great Ill test it tomorrow.
